services:
  frontend:
    container_name: moiras_front_dev
    image: moiras_front-dev
    stdin_open: true
    tty: true
    user: '${CURRENT_UID}:${CURRENT_GID}'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
      - '4173:4173'
    volumes:
      - .:/app
      - ~/.gitconfig:/home/node/.gitconfig:ro
      - ~/.ssh:/home/node/.ssh:ro
    environment:
      - GIT_SSH_COMMAND=ssh -o IdentitiesOnly=yes -F /dev/null
