services:
  frontend:
    container_name: moiras_front_dev
    image: moiras_front-dev
    stdin_open: true
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - ..:/app
